GET http://127.0.0.1:3000/cocktails
###
GET http://127.0.0.1:3000/cocktails/Alice/zutaten
###
GET http://127.0.0.1:3000/cocktails/preis/7.2
###
DELETE http://127.0.0.1:3000/cocktails/Hit and Run
###
POST http://127.0.0.1:3000/cocktails
Content-Type: application/json

{
    "cname": "Hit and Run",
    "preis": 12.22,
    "zubereitung": "eo ipso",
    "kid": 1,
    "zgid": 1,
    "sgid": 1
}
###
PATCH  http://127.0.0.1:3000/cocktails/preis
Content-Type: application/json

{
    "cname": "Hit and Run",
    "preis": 99.99
}